### ISSUE TITLE
Check if dependency in `gql` package is amended

### ISSUE THREAD

**Issue by euphoria108** [opthub-org/opthub-scorer#8]
[`gql` パッケージ](https://github.com/graphql-python/gql) のバージョン 3.0.0 が公開されたが、依存パッケージの記述に `requests_toolbelt` が欠けているため、そのまま使おうとするとエラーが出る。

現在は setup.cfg で
```
gql >= 2.0.0, < 3
```
と上限をつけることで対応しているが、依存パッケージの問題が解決されたら上限を外す。

**Comment by NaokiHamada** [comment]
デフォルトで`requests_toolbelt`がインストールされないのは[仕様](https://gql.readthedocs.io/en/latest/intro.html#less-dependencies)らしい。
```
gql[all]  # 全機能の依存パッケージをインストール
```
あるいは
```
gql[requests]  # 最小限の依存パッケージをインストール
```
とすればOK。

**Comment by NaokiHamada** [comment]
修正した
